services:
  mariadb:
    environment:
      MARIADB_USER: railsUser
      MARIADB_PASSWORD: railsPassword
      MARIADB_DATABASE: Grazer
      MARIADB_ROOT_PASSWORD: rootPassword
    image: mariadb:11.6
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 30
  api:
    build:
      context: ./api
    command: /bin/sh -c "rm -rf /app/tmp/pids/server.pid && bin/setup --skip-server && bin/rails server -b 0.0.0.0 -p 3000"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      APP_DATABASE_HOST: mariadb
      APP_DATABASE_USERNAME: railsUser
      APP_DATABASE_PASSWORD: railsPassword
      APP_DATABASE_NAME: Grazer
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./api:/app
      - bundler-store:/usr/local/bundle

volumes:
  bundler-store: