default: &default
  <<: *default
  database: <%= ENV.fetch("APP_DATABASE_NAME", 'Grazer') %>
  adapter: mysql2
  host: <%= ENV.fetch("APP_DATABASE_HOST", 'localhost') %>
  pool: <%= ENV.fetch("APP_RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("APP_DATABASE_USERNAME", 'railsUser') %>
  password: <%= ENV.fetch("APP_DATABASE_PASSWORD", 'railsPassword') %>
  timeout: 5000
  encoding: utf8
  port: 3306

development:
  <<: *default

test:
  <<: *default